global:
  scrape_interval: 4s

scrape_configs:
  - job_name: prometheus
    static_configs:
      # if this is running on a docker container, use the IP Address of your PC instead
      - targets: ["localhost:8000"]
